apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: control-plane
spec:
  template:
    spec:
      containers:
        - name: control-plane
          image: self-service-cicd-control-plane
          ports:
            - name: http
              containerPort: 8080
          lifecycle:
            preStop:
              exec: {command: ["/bin/sh", "-c", "sleep 5"]}
